version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repo-scm-proxy
    ports:
      - "9090:9090"
    volumes:
      - ./config:/app/config:ro
      - ~/.ssh:/root/.ssh:ro
    environment:
      - GO_ENV=production
    restart: unless-stopped
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # nginx:
  #   image: nginx:alpine
  #   container_name: repo-scm-proxy-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - proxy
  #   networks:
  #     - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  proxy-data:
    driver: local
